#!/bin/bash

list="issue spike task"

listRE="^($(printf '%s\n' "$list" | tr ' ' '|'))/"

BRANCH_NAME=$(git branch --show-current | grep -E "$listRE" | sed 's/* //')

printf '\n\033[0;105mChecking "%s"... \033[0m\n' "$BRANCH_NAME"

if echo "$BRANCH_NAME" | grep -q '^(hotfix)|(rebase)|(production)*$'; then
 	printf '\n\033[0;32mNo checks necessary on "%s", skipping hooks... 🎉\033[0m\n' "$BRANCH_NAME"
	exit 0
fi


if ! git update-index -q --ignore-submodules --refresh
then
	printf '\n\033[0;31mUp-to-date check failed😖\033[0m\n'
  DOCKER_EXIT_CODE=0
else
  make image
  DOCKER_EXIT_CODE=$?
fi

if [ $DOCKER_EXIT_CODE -eq 0 ]; then
  printf '\n\033[0;31mDocker image build failed. Please check your changes. 😖\033[0m\n'
  exit 1
fi

if [ $DOCKER_EXIT_CODE -ne 0 ]; then
  printf '\n\033[0;32mDocker image build succeeded. 🎉\033[0m\n'
fi

exit 0
