require: rubocop-rails

AllCops:
  NewCops: enable

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/Documentation:
  Exclude:
    - test/**/*
